USE TRAVEL;

SHOW TABLES;

DESCRIBE BOARD;
DESCRIBE BOOKMARK;
DESCRIBE CATEGORY;
DESCRIBE COMMENT;
DESCRIBE HISTORY;
DESCRIBE KIND;
DESCRIBE `LIKE`;
DESCRIBE `live-rank`;
DESCRIBE `main-photo`;
DESCRIBE mark;
DESCRIBE member;
DESCRIBE photo;
DESCRIBE `report=box`;
DESCRIBE review;
DESCRIBE travel;